const MATCH_DATA = [
{
"id": "1",
"bjDate": "2026-06-12 02:00",
"home": "Mexico",
"away": "South Africa",
"homeCn": "墨西哥",
"awayCn": "南非",
"homeFlag": "mx",
"awayFlag": "za",
"homeScore": 2,
"awayScore": 0,
"phase": "小组赛",
"status": "finished",
"stadiumId": "1"
},
{
"id": "2",
"bjDate": "2026-06-12 09:00",
"home": "South Korea",
"away": "Czech Republic",
"homeCn": "韩国",
"awayCn": "捷克",
"homeFlag": "kr",
"awayFlag": "cz",
"homeScore": 2,
"awayScore": 1,
"phase": "小组赛",
"status": "finished",
"stadiumId": "2"
},
{
"id": "3",
"bjDate": "2026-06-13 03:00",
"home": "Canada",
"away": "Bosnia and Herzegovina",
"homeCn": "加拿大",
"awayCn": "波黑",
"homeFlag": "ca",
"awayFlag": "ba",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "12"
},
{
"id": "4",
"bjDate": "2026-06-13 09:00",
"home": "United States",
"away": "Paraguay",
"homeCn": "美国",
"awayCn": "巴拉圭",
"homeFlag": "us",
"awayFlag": "py",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "16"
},
{
"id": "5",
"bjDate": "2026-06-14 09:00",
"home": "Haiti",
"away": "Scotland",
"homeCn": "海地",
"awayCn": "苏格兰",
"homeFlag": "ht",
"awayFlag": "gb-sct",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "9"
},
{
"id": "6",
"bjDate": "2026-06-14 12:00",
"home": "Australia",
"away": "Turkey",
"homeCn": "澳大利亚",
"awayCn": "土耳其",
"homeFlag": "au",
"awayFlag": "tr",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "13"
},
{
"id": "7",
"bjDate": "2026-06-14 06:00",
"home": "Brazil",
"away": "Morocco",
"homeCn": "巴西",
"awayCn": "摩洛哥",
"homeFlag": "br",
"awayFlag": "ma",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "11"
},
{
"id": "8",
"bjDate": "2026-06-14 03:00",
"home": "Qatar",
"away": "Switzerland",
"homeCn": "卡塔尔",
"awayCn": "瑞士",
"homeFlag": "qa",
"awayFlag": "ch",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "15"
},
{
"id": "9",
"bjDate": "2026-06-15 07:00",
"home": "Ivory Coast",
"away": "Ecuador",
"homeCn": "科特迪瓦",
"awayCn": "厄瓜多尔",
"homeFlag": "ci",
"awayFlag": "ec",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "10"
},
{
"id": "10",
"bjDate": "2026-06-15 01:00",
"home": "Germany",
"away": "Curaçao",
"homeCn": "德国",
"awayCn": "库拉索",
"homeFlag": "de",
"awayFlag": "cw",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "5"
},
{
"id": "11",
"bjDate": "2026-06-15 04:00",
"home": "Netherlands",
"away": "Japan",
"homeCn": "荷兰",
"awayCn": "日本",
"homeFlag": "nl",
"awayFlag": "jp",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "4"
},
{
"id": "12",
"bjDate": "2026-06-15 09:00",
"home": "Sweden",
"away": "Tunisia",
"homeCn": "瑞典",
"awayCn": "突尼斯",
"homeFlag": "se",
"awayFlag": "tn",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "3"
},
{
"id": "13",
"bjDate": "2026-06-16 09:00",
"home": "Iran",
"away": "New Zealand",
"homeCn": "伊朗",
"awayCn": "新西兰",
"homeFlag": "ir",
"awayFlag": "nz",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "16"
},
{
"id": "14",
"bjDate": "2026-06-16 00:00",
"home": "Spain",
"away": "Cape Verde",
"homeCn": "西班牙",
"awayCn": "佛得角",
"homeFlag": "es",
"awayFlag": "cv",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "7"
},
{
"id": "15",
"bjDate": "2026-06-16 03:00",
"home": "Belgium",
"away": "Egypt",
"homeCn": "比利时",
"awayCn": "埃及",
"homeFlag": "be",
"awayFlag": "eg",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "14"
},
{
"id": "16",
"bjDate": "2026-06-16 06:00",
"home": "Saudi Arabia",
"away": "Uruguay",
"homeCn": "沙特",
"awayCn": "乌拉圭",
"homeFlag": "sa",
"awayFlag": "uy",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "8"
},
{
"id": "17",
"bjDate": "2026-06-17 03:00",
"home": "France",
"away": "Senegal",
"homeCn": "法国",
"awayCn": "塞内加尔",
"homeFlag": "fr",
"awayFlag": "sn",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "11"
},
{
"id": "18",
"bjDate": "2026-06-17 06:00",
"home": "Iraq",
"away": "Norway",
"homeCn": "伊拉克",
"awayCn": "挪威",
"homeFlag": "iq",
"awayFlag": "no",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "9"
},
{
"id": "19",
"bjDate": "2026-06-17 09:00",
"home": "Argentina",
"away": "Algeria",
"homeCn": "阿根廷",
"awayCn": "阿尔及利亚",
"homeFlag": "ar",
"awayFlag": "dz",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "6"
},
{
"id": "20",
"bjDate": "2026-06-17 12:00",
"home": "Austria",
"away": "Jordan",
"homeCn": "奥地利",
"awayCn": "约旦",
"homeFlag": "at",
"awayFlag": "jo",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "15"
},
{
"id": "21",
"bjDate": "2026-06-18 01:00",
"home": "Portugal",
"away": "Democratic Republic of the Congo",
"homeCn": "葡萄牙",
"awayCn": "民主刚果",
"homeFlag": "pt",
"awayFlag": "cd",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "5"
},
{
"id": "22",
"bjDate": "2026-06-18 04:00",
"home": "England",
"away": "Croatia",
"homeCn": "英格兰",
"awayCn": "克罗地亚",
"homeFlag": "gb-eng",
"awayFlag": "hr",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "4"
},
{
"id": "23",
"bjDate": "2026-06-18 09:00",
"home": "Uzbekistan",
"away": "Colombia",
"homeCn": "乌兹别克斯坦",
"awayCn": "哥伦比亚",
"homeFlag": "uz",
"awayFlag": "co",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "1"
},
{
"id": "24",
"bjDate": "2026-06-18 07:00",
"home": "Ghana",
"away": "Panama",
"homeCn": "加纳",
"awayCn": "巴拿马",
"homeFlag": "gh",
"awayFlag": "pa",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "12"
},
{
"id": "25",
"bjDate": "2026-06-19 08:00",
"home": "Mexico",
"away": "South Korea",
"homeCn": "墨西哥",
"awayCn": "韩国",
"homeFlag": "mx",
"awayFlag": "kr",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "2"
},
{
"id": "26",
"bjDate": "2026-06-19 03:00",
"home": "Switzerland",
"away": "Bosnia and Herzegovina",
"homeCn": "瑞士",
"awayCn": "波黑",
"homeFlag": "ch",
"awayFlag": "ba",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "16"
},
{
"id": "27",
"bjDate": "2026-06-19 06:00",
"home": "Canada",
"away": "Qatar",
"homeCn": "加拿大",
"awayCn": "卡塔尔",
"homeFlag": "ca",
"awayFlag": "qa",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "13"
},
{
"id": "28",
"bjDate": "2026-06-19 00:00",
"home": "Czech Republic",
"away": "South Africa",
"homeCn": "捷克",
"awayCn": "南非",
"homeFlag": "cz",
"awayFlag": "za",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "7"
},
{
"id": "29",
"bjDate": "2026-06-20 09:00",
"home": "Brazil",
"away": "Haiti",
"homeCn": "巴西",
"awayCn": "海地",
"homeFlag": "br",
"awayFlag": "ht",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "10"
},
{
"id": "30",
"bjDate": "2026-06-20 06:00",
"home": "Scotland",
"away": "Morocco",
"homeCn": "苏格兰",
"awayCn": "摩洛哥",
"homeFlag": "gb-sct",
"awayFlag": "ma",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "9"
},
{
"id": "31",
"bjDate": "2026-06-20 03:00",
"home": "United States",
"away": "Australia",
"homeCn": "美国",
"awayCn": "澳大利亚",
"homeFlag": "us",
"awayFlag": "au",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "14"
},
{
"id": "32",
"bjDate": "2026-06-20 11:00",
"home": "Turkey",
"away": "Paraguay",
"homeCn": "土耳其",
"awayCn": "巴拉圭",
"homeFlag": "tr",
"awayFlag": "py",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "15"
},
{
"id": "33",
"bjDate": "2026-06-21 04:00",
"home": "Germany",
"away": "Ivory Coast",
"homeCn": "德国",
"awayCn": "科特迪瓦",
"homeFlag": "de",
"awayFlag": "ci",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "12"
},
{
"id": "34",
"bjDate": "2026-06-21 08:00",
"home": "Ecuador",
"away": "Curaçao",
"homeCn": "厄瓜多尔",
"awayCn": "库拉索",
"homeFlag": "ec",
"awayFlag": "cw",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "6"
},
{
"id": "35",
"bjDate": "2026-06-21 01:00",
"home": "Netherlands",
"away": "Sweden",
"homeCn": "荷兰",
"awayCn": "瑞典",
"homeFlag": "nl",
"awayFlag": "se",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "5"
},
{
"id": "36",
"bjDate": "2026-06-21 11:00",
"home": "Tunisia",
"away": "Japan",
"homeCn": "突尼斯",
"awayCn": "日本",
"homeFlag": "tn",
"awayFlag": "jp",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "3"
},
{
"id": "37",
"bjDate": "2026-06-22 03:00",
"home": "Belgium",
"away": "Iran",
"homeCn": "比利时",
"awayCn": "伊朗",
"homeFlag": "be",
"awayFlag": "ir",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "16"
},
{
"id": "38",
"bjDate": "2026-06-22 09:00",
"home": "New Zealand",
"away": "Egypt",
"homeCn": "新西兰",
"awayCn": "埃及",
"homeFlag": "nz",
"awayFlag": "eg",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "13"
},
{
"id": "39",
"bjDate": "2026-06-22 00:00",
"home": "Spain",
"away": "Saudi Arabia",
"homeCn": "西班牙",
"awayCn": "沙特",
"homeFlag": "es",
"awayFlag": "sa",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "7"
},
{
"id": "40",
"bjDate": "2026-06-22 06:00",
"home": "Uruguay",
"away": "Cape Verde",
"homeCn": "乌拉圭",
"awayCn": "佛得角",
"homeFlag": "uy",
"awayFlag": "cv",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "8"
},
{
"id": "41",
"bjDate": "2026-06-23 05:00",
"home": "France",
"away": "Iraq",
"homeCn": "法国",
"awayCn": "伊拉克",
"homeFlag": "fr",
"awayFlag": "iq",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "10"
},
{
"id": "42",
"bjDate": "2026-06-23 08:00",
"home": "Norway",
"away": "Senegal",
"homeCn": "挪威",
"awayCn": "塞内加尔",
"homeFlag": "no",
"awayFlag": "sn",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "11"
},
{
"id": "43",
"bjDate": "2026-06-23 01:00",
"home": "Argentina",
"away": "Austria",
"homeCn": "阿根廷",
"awayCn": "奥地利",
"homeFlag": "ar",
"awayFlag": "at",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "4"
},
{
"id": "44",
"bjDate": "2026-06-23 11:00",
"home": "Jordan",
"away": "Algeria",
"homeCn": "约旦",
"awayCn": "阿尔及利亚",
"homeFlag": "jo",
"awayFlag": "dz",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "15"
},
{
"id": "45",
"bjDate": "2026-06-24 01:00",
"home": "Portugal",
"away": "Uzbekistan",
"homeCn": "葡萄牙",
"awayCn": "乌兹别克斯坦",
"homeFlag": "pt",
"awayFlag": "uz",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "5"
},
{
"id": "46",
"bjDate": "2026-06-24 07:00",
"home": "Panama",
"away": "Croatia",
"homeCn": "巴拿马",
"awayCn": "克罗地亚",
"homeFlag": "pa",
"awayFlag": "hr",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "12"
},
{
"id": "47",
"bjDate": "2026-06-24 09:00",
"home": "Colombia",
"away": "Democratic Republic of the Congo",
"homeCn": "哥伦比亚",
"awayCn": "民主刚果",
"homeFlag": "co",
"awayFlag": "cd",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "2"
},
{
"id": "48",
"bjDate": "2026-06-24 04:00",
"home": "England",
"away": "Ghana",
"homeCn": "英格兰",
"awayCn": "加纳",
"homeFlag": "gb-eng",
"awayFlag": "gh",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "9"
},
{
"id": "49",
"bjDate": "2026-06-25 06:00",
"home": "Scotland",
"away": "Brazil",
"homeCn": "苏格兰",
"awayCn": "巴西",
"homeFlag": "gb-sct",
"awayFlag": "br",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "8"
},
{
"id": "50",
"bjDate": "2026-06-25 06:00",
"home": "Morocco",
"away": "Haiti",
"homeCn": "摩洛哥",
"awayCn": "海地",
"homeFlag": "ma",
"awayFlag": "ht",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "7"
},
{
"id": "51",
"bjDate": "2026-06-25 08:00",
"home": "South Africa",
"away": "South Korea",
"homeCn": "南非",
"awayCn": "韩国",
"homeFlag": "za",
"awayFlag": "kr",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "3"
},
{
"id": "52",
"bjDate": "2026-06-25 08:00",
"home": "Czech Republic",
"away": "Mexico",
"homeCn": "捷克",
"awayCn": "墨西哥",
"homeFlag": "cz",
"awayFlag": "mx",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "1"
},
{
"id": "53",
"bjDate": "2026-06-25 03:00",
"home": "Bosnia and Herzegovina",
"away": "Qatar",
"homeCn": "波黑",
"awayCn": "卡塔尔",
"homeFlag": "ba",
"awayFlag": "qa",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "14"
},
{
"id": "54",
"bjDate": "2026-06-25 03:00",
"home": "Switzerland",
"away": "Canada",
"homeCn": "瑞士",
"awayCn": "加拿大",
"homeFlag": "ch",
"awayFlag": "ca",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "13"
},
{
"id": "55",
"bjDate": "2026-06-26 04:00",
"home": "Curaçao",
"away": "Ivory Coast",
"homeCn": "库拉索",
"awayCn": "科特迪瓦",
"homeFlag": "cw",
"awayFlag": "ci",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "10"
},
{
"id": "56",
"bjDate": "2026-06-26 04:00",
"home": "Ecuador",
"away": "Germany",
"homeCn": "厄瓜多尔",
"awayCn": "德国",
"homeFlag": "ec",
"awayFlag": "de",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "11"
},
{
"id": "57",
"bjDate": "2026-06-26 10:00",
"home": "Paraguay",
"away": "Australia",
"homeCn": "巴拉圭",
"awayCn": "澳大利亚",
"homeFlag": "py",
"awayFlag": "au",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "15"
},
{
"id": "58",
"bjDate": "2026-06-26 10:00",
"home": "Turkey",
"away": "United States",
"homeCn": "土耳其",
"awayCn": "美国",
"homeFlag": "tr",
"awayFlag": "us",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "16"
},
{
"id": "59",
"bjDate": "2026-06-26 07:00",
"home": "Japan",
"away": "Sweden",
"homeCn": "日本",
"awayCn": "瑞典",
"homeFlag": "jp",
"awayFlag": "se",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "4"
},
{
"id": "60",
"bjDate": "2026-06-26 07:00",
"home": "Tunisia",
"away": "Netherlands",
"homeCn": "突尼斯",
"awayCn": "荷兰",
"homeFlag": "tn",
"awayFlag": "nl",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "6"
},
{
"id": "61",
"bjDate": "2026-06-27 03:00",
"home": "Senegal",
"away": "Iraq",
"homeCn": "塞内加尔",
"awayCn": "伊拉克",
"homeFlag": "sn",
"awayFlag": "iq",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "12"
},
{
"id": "62",
"bjDate": "2026-06-27 03:00",
"home": "Norway",
"away": "France",
"homeCn": "挪威",
"awayCn": "法国",
"homeFlag": "no",
"awayFlag": "fr",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "9"
},
{
"id": "63",
"bjDate": "2026-06-27 11:00",
"home": "Egypt",
"away": "Iran",
"homeCn": "埃及",
"awayCn": "伊朗",
"homeFlag": "eg",
"awayFlag": "ir",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "14"
},
{
"id": "64",
"bjDate": "2026-06-27 11:00",
"home": "New Zealand",
"away": "Belgium",
"homeCn": "新西兰",
"awayCn": "比利时",
"homeFlag": "nz",
"awayFlag": "be",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "13"
},
{
"id": "65",
"bjDate": "2026-06-27 08:00",
"home": "Cape Verde",
"away": "Saudi Arabia",
"homeCn": "佛得角",
"awayCn": "沙特",
"homeFlag": "cv",
"awayFlag": "sa",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "5"
},
{
"id": "66",
"bjDate": "2026-06-27 07:00",
"home": "Uruguay",
"away": "Spain",
"homeCn": "乌拉圭",
"awayCn": "西班牙",
"homeFlag": "uy",
"awayFlag": "es",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "2"
},
{
"id": "67",
"bjDate": "2026-06-28 05:00",
"home": "Panama",
"away": "England",
"homeCn": "巴拿马",
"awayCn": "英格兰",
"homeFlag": "pa",
"awayFlag": "gb-eng",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "11"
},
{
"id": "68",
"bjDate": "2026-06-28 05:00",
"home": "Croatia",
"away": "Ghana",
"homeCn": "克罗地亚",
"awayCn": "加纳",
"homeFlag": "hr",
"awayFlag": "gh",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "10"
},
{
"id": "69",
"bjDate": "2026-06-28 10:00",
"home": "Algeria",
"away": "Austria",
"homeCn": "阿尔及利亚",
"awayCn": "奥地利",
"homeFlag": "dz",
"awayFlag": "at",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "6"
},
{
"id": "70",
"bjDate": "2026-06-28 10:00",
"home": "Jordan",
"away": "Argentina",
"homeCn": "约旦",
"awayCn": "阿根廷",
"homeFlag": "jo",
"awayFlag": "ar",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "4"
},
{
"id": "71",
"bjDate": "2026-06-28 07:30",
"home": "Colombia",
"away": "Portugal",
"homeCn": "哥伦比亚",
"awayCn": "葡萄牙",
"homeFlag": "co",
"awayFlag": "pt",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "8"
},
{
"id": "72",
"bjDate": "2026-06-28 07:30",
"home": "Democratic Republic of the Congo",
"away": "Uzbekistan",
"homeCn": "民主刚果",
"awayCn": "乌兹别克斯坦",
"homeFlag": "cd",
"awayFlag": "uz",
"homeScore": null,
"awayScore": null,
"phase": "小组赛",
"status": "upcoming",
"stadiumId": "7"
},
{
"id": "73",
"bjDate": "2026-06-29 03:00",
"home": "South Africa",
"away": "Canada",
"homeCn": "南非",
"awayCn": "加拿大",
"homeFlag": "za",
"awayFlag": "ca",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "16"
},
{
"id": "74",
"bjDate": "2026-06-30 04:30",
"home": "Germany",
"away": "Paraguay",
"homeCn": "德国",
"awayCn": "巴拉圭",
"homeFlag": "br",
"awayFlag": "jp",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "9"
},
{
"id": "75",
"bjDate": "2026-06-30 09:00",
"home": "Netherlands",
"away": "Morocco",
"homeCn": "荷兰",
"awayCn": "摩洛哥",
"homeFlag": "de",
"awayFlag": "py",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "3"
},
{
"id": "76",
"bjDate": "2026-06-30 01:00",
"home": "Brazil",
"away": "Japan",
"homeCn": "巴西",
"awayCn": "日本",
"homeFlag": "nl",
"awayFlag": "ma",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "5"
},
{
"id": "77",
"bjDate": "2026-07-01 05:00",
"home": "France",
"away": "Sweden",
"homeCn": "法国",
"awayCn": "瑞典",
"homeFlag": "ci",
"awayFlag": "no",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "11"
},
{
"id": "78",
"bjDate": "2026-07-01 01:00",
"home": "Ivory Coast",
"away": "Norway",
"homeCn": "科特迪瓦",
"awayCn": "挪威",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "4"
},
{
"id": "79",
"bjDate": "2026-07-01 10:00",
"home": "Mexico",
"away": "Ecuador",
"homeCn": "墨西哥",
"awayCn": "厄瓜多尔",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "1"
},
{
"id": "80",
"bjDate": "2026-07-02 00:00",
"home": "England",
"away": "Democratic Republic of the Congo",
"homeCn": "英格兰",
"awayCn": "民主刚果",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "7"
},
{
"id": "81",
"bjDate": "2026-07-02 08:00",
"home": "United States",
"away": "Bosnia and Herzegovina",
"homeCn": "美国",
"awayCn": "波黑",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "15"
},
{
"id": "82",
"bjDate": "2026-07-02 04:00",
"home": "Belgium",
"away": "Senegal",
"homeCn": "比利时",
"awayCn": "塞内加尔",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "14"
},
{
"id": "83",
"bjDate": "2026-07-03 07:00",
"home": "Portugal",
"away": "Croatia",
"homeCn": "葡萄牙",
"awayCn": "克罗地亚",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "12"
},
{
"id": "84",
"bjDate": "2026-07-03 03:00",
"home": "Spain",
"away": "Austria",
"homeCn": "西班牙",
"awayCn": "奥地利",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "16"
},
{
"id": "85",
"bjDate": "2026-07-03 11:00",
"home": "Switzerland",
"away": "Algeria",
"homeCn": "瑞士",
"awayCn": "阿尔及利亚",
"homeFlag": "au",
"awayFlag": "eg",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "13"
},
{
"id": "86",
"bjDate": "2026-07-04 06:00",
"home": "Argentina",
"away": "Cape Verde",
"homeCn": "阿根廷",
"awayCn": "佛得角",
"homeFlag": "ar",
"awayFlag": "cv",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "8"
},
{
"id": "87",
"bjDate": "2026-07-04 09:30",
"home": "Colombia",
"away": "Ghana",
"homeCn": "哥伦比亚",
"awayCn": "加纳",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "6"
},
{
"id": "88",
"bjDate": "2026-07-04 02:00",
"home": "Australia",
"away": "Egypt",
"homeCn": "澳大利亚",
"awayCn": "埃及",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "十六分之一决赛",
"status": "upcoming",
"stadiumId": "4"
},
{
"id": "89",
"bjDate": "2026-07-05 05:00",
"home": "Paraguay",
"away": "France",
"homeCn": "巴拉圭",
"awayCn": "法国",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "八分之一决赛",
"status": "upcoming",
"stadiumId": "10"
},
{
"id": "90",
"bjDate": "2026-07-05 01:00",
"home": "Canada",
"away": "Morocco",
"homeCn": "加拿大",
"awayCn": "摩洛哥",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "八分之一决赛",
"status": "upcoming",
"stadiumId": "5"
},
{
"id": "91",
"bjDate": "2026-07-06 04:00",
"home": "Brazil",
"away": "Norway",
"homeCn": "巴西",
"awayCn": "挪威",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "八分之一决赛",
"status": "upcoming",
"stadiumId": "11"
},
{
"id": "92",
"bjDate": "2026-07-06 09:00",
"home": "Mexico",
"away": "England",
"homeCn": "墨西哥",
"awayCn": "英格兰",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "八分之一决赛",
"status": "upcoming",
"stadiumId": "1"
},
{
"id": "93",
"bjDate": "2026-07-07 03:00",
"home": "Portugal",
"away": "Spain",
"homeCn": "葡萄牙",
"awayCn": "西班牙",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "八分之一决赛",
"status": "upcoming",
"stadiumId": "4"
},
{
"id": "94",
"bjDate": "2026-07-07 08:00",
"home": "United States",
"away": "Belgium",
"homeCn": "美国",
"awayCn": "比利时",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "八分之一决赛",
"status": "upcoming",
"stadiumId": "14"
},
{
"id": "95",
"bjDate": "2026-07-08 00:00",
"home": "Argentina",
"away": "Egypt",
"homeCn": "阿根廷",
"awayCn": "埃及",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "八分之一决赛",
"status": "upcoming",
"stadiumId": "7"
},
{
"id": "96",
"bjDate": "2026-07-08 04:00",
"home": "Switzerland",
"away": "Colombia",
"homeCn": "瑞士",
"awayCn": "哥伦比亚",
"homeFlag": "",
"awayFlag": "",
"homeScore": null,
"awayScore": null,
"phase": "八分之一决赛",
"status": "upcoming",
"stadiumId": "13"
},
{
"id": "97",
"bjDate": "2026-07-10 04:00",
"home": "France",
"away": "Morocco",
"homeCn": "法国",
"awayCn": "摩洛哥",
"homeFlag": "fr",
"awayFlag": "ma",
"homeScore": null,
"awayScore": null,
"phase": "四分之一决赛",
"status": "upcoming",
"stadiumId": "9"
},
{
"id": "98",
"bjDate": "2026-07-11 03:00",
"home": "Spain",
"away": "Belgium",
"homeCn": "西班牙",
"awayCn": "比利时",
"homeFlag": "es",
"awayFlag": "be",
"homeScore": null,
"awayScore": null,
"phase": "四分之一决赛",
"status": "upcoming",
"stadiumId": "16"
},
{
"id": "99",
"bjDate": "2026-07-12 05:00",
"home": "Norway",
"away": "England",
"homeCn": "挪威",
"awayCn": "英格兰",
"homeFlag": "no",
"awayFlag": "gb-eng",
"homeScore": null,
"awayScore": null,
"phase": "四分之一决赛",
"status": "upcoming",
"stadiumId": "8"
},
{
"id": "100",
"bjDate": "2026-07-12 09:00",
"home": "Argentina",
"away": "Switzerland",
"homeCn": "阿根廷",
"awayCn": "瑞士",
"homeFlag": "ar",
"awayFlag": "ch",
"homeScore": null,
"awayScore": null,
"phase": "四分之一决赛",
"status": "upcoming",
"stadiumId": "6"
},
{
"id": "101",
"bjDate": "2026-07-15 03:00",
"home": "France",
"away": "Spain",
"homeCn": "法国",
"awayCn": "西班牙",
"homeFlag": "fr",
"awayFlag": "es",
"homeScore": null,
"awayScore": null,
"phase": "半决赛",
"status": "upcoming",
"stadiumId": "4",
"xFactors": [
{"id":1,"q":"姆巴佩能否在非点球决胜期间进球？","opts":["是","否"],"mode":"manual","metric":"mbappeGoal","op":">=","threshold":1,"win":5,"lose":-5},
{"id":2,"q":"常规时间是否有点球判罚？","opts":["是","否"],"mode":"manual","metric":"penaltyAwarded","op":">=","threshold":1,"win":5,"lose":-5},
{"id":3,"q":"上半场(45')是否有进球？","opts":["是","否"],"mode":"manual","metric":"firstHalfGoal","op":">=","threshold":1,"win":5,"lose":-5}
]
},
{
"id": "102",
"bjDate": "2026-07-16 03:00",
"home": "England",
"away": "Argentina",
"homeCn": "英格兰",
"awayCn": "阿根廷",
"homeFlag": "gb-eng",
"awayFlag": "ar",
"homeScore": null,
"awayScore": null,
"phase": "半决赛",
"status": "upcoming",
"stadiumId": "7",
"xFactors": [
{"id":1,"q":"上下半场的伤停补时时间会不会进球？","opts":["是","否"],"mode":"auto","metric":"regInjuryGoalAny","win":5,"lose":-5},
{"id":2,"q":"所有比赛时间里的黄牌数量是否≥6？（1红按2黄计）","opts":["是","否"],"mode":"manual","metric":"yellowTotal","op":">=","threshold":6,"win":5,"lose":-5},
{"id":3,"q":"阿根廷会进第一个球么？","opts":["会","不会"],"mode":"auto","metric":"awayFirstGoal","win":5,"lose":-5}
]
},
{
"id": "103",
"bjDate": "2026-07-19 05:00",
"home": "France",
"away": "England",
"homeCn": "法国",
"awayCn": "英格兰",
"homeFlag": "fr",
"awayFlag": "gb-eng",
"homeScore": null,
"awayScore": null,
"phase": "季军赛",
"status": "upcoming",
"stadiumId": "8",
"xFactors": [
{"id":1,"q":"季军战是养生局还是刺刀见红？常规时间总进球≥4？","opts":["是","否"],"mode":"auto","metric":"regTotalGE","threshold":4,"win":6,"lose":-6},
{"id":2,"q":"未晋级发泄+英法世仇，本场会不会有人因脱衣庆祝/庆祝过火被黄牌（或红牌）？","opts":["会","不会"],"mode":"manual","metric":"celebCard","op":">=","threshold":1,"win":6,"lose":-6},
{"id":3,"q":"难解难分或是士气涣散，英法季军战会不会踢到点球大战？","opts":["是","否"],"mode":"auto","metric":"penalties","win":6,"lose":-6}
]
},
{
"id": "104",
"bjDate": "2026-07-20 03:00",
"home": "Spain",
"away": "Argentina",
"homeCn": "西班牙",
"awayCn": "阿根廷",
"homeFlag": "es",
"awayFlag": "ar",
"homeScore": 1,
"awayScore": 0,
"phase": "决赛",
"status": "finished",
"settledDate": "2026-07-20",
"reveal": true,
"stadiumId": "11",
"xFactors": [
{"id":1,"q":"宗主对决，常规时间总进球≥2？","opts":["是","否"],"mode":"auto","metric":"regTotalGE","threshold":2,"win":7,"lose":-7},
{"id":2,"q":"一剑封喉，决赛是否拖入点球大战？","opts":["是","否"],"mode":"auto","metric":"penalties","win":7,"lose":-7},
{"id":3,"q":"不落后就不会踢，阿根廷再次先落后一球？","opts":["是","否"],"mode":"auto","metric":"homeFirstGoal","win":7,"lose":-7},
{"id":4,"q":"感谢编程组织者，与我共度美好时光，我愿意请客一次？","opts":["愿意（+10）","不愿意（-10）"],"mode":"manual","metric":"treat","op":">=","threshold":1,"win":10,"lose":-10,"hideChoices":true}
]
}
];